### ISSUE TITLE
Conflict with Shibboleth SSO; use on select sites in MultiSite?

### ISSUE THREAD

**Issue by MadtownLems** [kovshenin/page-caching#32]
Hi there,

Surge has been working awesomely for me, but I just realized it breaks ours sites that require users be logged in to view, which are handled by Shibboleth: https://www.shibboleth.net/about-us/the-shibboleth-project/

We run MultiSites, and per your suggestions, have been Network Activating Surge.  (https://wordpress.org/support/topic/multisite-636/)

Again, in most cases, it's been working awesomely. However, on the sites that have front-ends that require users to be logged in, users end up in an infinite redirect loop.

I'm assuming that figuring out WHY it's not working with Shibboleth is out of scope for support, though I'd be happy to connect with you directly and chat about that.  Here are some questions that I do have, however:

1) You wrote "The plugin should be network-activated to work correctly."  In my basic testing, it appears to work fine when activated on a site-by-site basis. Are you able to elaborate on what does or might not work correctly if it's not network activated? The ability to control which sites it's actually used on would be AMAZING for our environments, where some sites are being updated almost constantly, and some haven't been updated in years.

2) If it's not possible to use it on a site-by-site basis per above, might it be possible to hook into part of the cache loading process and opt out if certain conditions are met?  Something like:

```
add_action( 'something_super_duper_early', 'maybe_not_use_surge');

function maybe_not_use_surge( ) {
 if ( $this_site_requires_being_logged_in_to_view ) {
   dont_use_surge_for_this_request();
 }
}
```

Thank you so much for your time and knowledge!

**Comment by kovshenin** [comment]
There's a single entry point (drop-in) for the entire network in Multisite, so the plugin should be enabled for all sites, otherwise it may lead to a situation where part of the code is executed for a site, but the other part is not because the plugin is deactivated.

You can serve a `Cache-Control: no-cache` header if you'd like Surge to not cache the current request. Alternatively, you could always vary the `WP_CACHE` definition in your wp-config.php file based on the current `$_SERVER['HTTP_HOST']` for example.

Hope that helps!

**Comment by MadtownLems** [comment]
Thanks, kovshenin!

The HTTP_HOST approach won't work for us because we have hundreds of sites that share a domain (subfolder install), but I was able to use nocache_headers() in our plugin that requires SSO logins and that seems to be working. 

Cheers!
