### ISSUE TITLE
PHP error logs have numerous: stat failed...

### ISSUE THREAD

**Issue by MadtownLems** [kovshenin/page-caching#33]
My error logs are getting a couple dozen of these a day, and was wondering if you knew what might be going on. They cover a large variety of subsites and different files in the /wp-content/cache/surge/ directory.

PHP WARNING: [stat(): stat failed for /home/account_name/public_html/wp-content/cache/surge/72/d3277e3b90f60fd2f6b08d9628a4a272.VJgk7M.php] in file /home/account_name/public_html/wp-content/plugins/surge/include/cron.php:50 at https://mynetwork.com/subsite/wp-cron.php?doing_wp_cron=1690921598.2740859985351562500000

**Comment by kovshenin** [comment]
The way Surge cleanup works is it scans the whole cache directory for files, and walks each file one by one. The problem is that by the time the file reaches its turn, it sometimes is already renamed or removed. Can probably do better at identifying temporary files before trying to `stat()` them, they do have a .{randomhash}.php ending.
